server:
  port: 8031
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 5f98f104-d5ae-4161-b843-8351811bb4a0
        group: DEV_GROUP
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        prefix: ${spring.application.name}-${spring.profiles.active}
        namespace: 5f98f104-d5ae-4161-b843-8351811bb4a0
        group: DEV_GROUP
  config:
    import: optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/system
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      timeout: 3000
      password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
gateway:
  filter:
    allowPaths:
      - /login
      - /api/auth


